# Generated by Django 5.2.13 on 2026-05-01 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='members',
            field=models.ManyToManyField(related_name='chats', through='chats.ChatMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='chatmember',
            constraint=models.UniqueConstraint(fields=('chat', 'user'), name='unique_chat_member'),
        ),
    ]
