# Generated by Django 5.2.13 on 2026-05-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('message_type', models.CharField(choices=[('question', 'Question'), ('task', 'Task'), ('default', 'Default')], default='default', max_length=20)),
                ('task_status', models.CharField(choices=[('none', 'None'), ('todo', 'Todo'), ('in_progress', 'In progress'), ('done', 'Done')], default='none', max_length=20)),
                ('analyst_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
