name: aimessenger

services:
  traefik:
    image: traefik:3.6.9
    container_name: traefik
    ports:
      - "80:80"
      - "8080:8080"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.web.address=:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - backend
    depends_on:
      backend:
        condition: service_started

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./.env:/app/.env:ro
      - aimessenger_static_data:/app/staticfiles
      - aimessenger_media_data:/app/media
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
      ML_CELERY_QUEUE: ml
      BACKEND_CELERY_QUEUE: backend
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    entrypoint: /app/entrypoint.sh
    networks:
      - backend
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy

  backend-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-worker
    volumes:
      - ./.env:/app/.env:ro
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
      ML_CELERY_QUEUE: ml
      BACKEND_CELERY_QUEUE: backend
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    command: celery -A config worker -Q backend --loglevel=info
    networks:
      - backend
    depends_on:
      ml-worker:
        condition: service_started
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: "http://localhost:8000"
    container_name: frontend
    ports:
      - "3000:80"
    networks:
      - backend
    depends_on:
      backend:
        condition: service_started

  ml-worker:
    build:
      context: ./ml-service
      dockerfile: Dockerfile
    container_name: ml-worker
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
      CELERY_QUEUE: ml
    networks:
      - backend
    depends_on:
      redis:
        condition: service_healthy

  postgres:
    image: pgvector/pgvector:pg18-trixie
    restart: always
    container_name: postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - aimessenger_postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 1s
      retries: 10
      start_period: 5s
      start_interval: 1s

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    command: >
      redis-server 
      --maxmemory 512mb 
      --maxmemory-policy allkeys-lru
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  aimessenger_postgres_data:
  aimessenger_static_data:
  aimessenger_media_data:

networks:
  backend:
    driver: bridge
