# Generated by Django 5.2.13 on 2026-05-11 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_accepted_privacy_policy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_contact_lists', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['contact__username'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'contact'), name='unique_user_contact'), models.CheckConstraint(condition=models.Q(('owner', models.F('contact')), _negated=True), name='prevent_self_contact')],
            },
        ),
    ]
